get_covariates_names <- function(data) {
  # extract the covariate columns from the data frame as is generated by generate_data in generate_data.R
  # we use this for all the following learners
  x_cols <- grep("^X", names(data), value = TRUE) # all columns beginning with X
  x_cols
}

fit_t_learner <- function(train_data, test_data, base_learner){
  # fit T-learner as introduced by Künzel et al. (2019)
  x_cols <- get_covariates_names(train_data)
  
  train0 <- train_data[train_data$T == 0,]
  train1 <- train_data[train_data$T == 1,]
  
  X0_train <- as.matrix(train0[, x_cols])
  X1_train <- as.matrix(train1[, x_cols])
  
  y0_train <- train0$Y
  y1_train <- train1$Y
  
  X_test <- as.matrix(test_data[, x_cols])
  
  # fit two separate base learners on the treated and untreated observations respectively as the T-learner requires
  model_0 <- base_learner$fit(X0_train, y0_train)
  model_1 <- base_learner$fit(X1_train, y1_train)
  
  # predict on the test set and then compute the final CATE estimate by taking the difference between the estimated responses
  mu0_hat <- base_learner$predict(model_0, X_test)
  mu1_hat <- base_learner$predict(model_1, X_test)
  
  tau_hat <- mu1_hat - mu0_hat
  
  list(
    tau_hat = tau_hat,
    mu0_hat = mu0_hat,
    mu1_hat = mu1_hat
  )
}

fit_x_learner <- function(train_data, test_data, base_learner){
  # fit X-learner as introduced by Künzel et al. (2019) with weight function g = pi_hat
  x_cols <- get_covariates_names(train_data)
  
  train0 <- train_data[train_data$T == 0,]
  train1 <- train_data[train_data$T == 1,]
  
  X0_train <- as.matrix(train0[, x_cols])
  X1_train <- as.matrix(train1[, x_cols])
  X_train <- as.matrix(train_data[, x_cols])
  
  y0_train <- train0$Y
  y1_train <- train1$Y
  
  X_test <- as.matrix(test_data[, x_cols])
  
  # fit response models and construct pseudo outcomes
  model_0 <- base_learner$fit(X0_train, y0_train)
  model_1 <- base_learner$fit(X1_train, y1_train)
  
  d0 <- base_learner$predict(model_1, X0_train) - y0_train
  d1 <- y1_train - base_learner$predict(model_0, X1_train)
  
  tau0_model <- base_learner$fit(X0_train, d0)
  tau1_model <- base_learner$fit(X1_train, d1)
  
  pi_model <- glm(T ~ ., data = train_data[, c("T", x_cols)], family = binomial())
  
  tau0_hat <- base_learner$predict(tau0_model, X_test)
  tau1_hat <- base_learner$predict(tau1_model, X_test)
  pi_hat <- predict(pi_model, newdata = test_data[, x_cols], type = "response")
  
  tau_hat <- pi_hat * tau0_hat + (1-pi_hat)* tau1_hat
  
  list(
    tau_hat = tau_hat,
    tau0_hat = tau0_hat,
    tau1_hat = tau1_hat
  )
}

fit_x_learner2 <- function(train_data, test_data, base_learner_mu, base_learner_tau){
  # fit X-learner as introduced by Künzel et al. (2019) with weight function g = pi_hat
  # allowing for two separate base learner classes for regression for mu and for regression for tau
  x_cols <- get_covariates_names(train_data)
  
  train0 <- train_data[train_data$T == 0,]
  train1 <- train_data[train_data$T == 1,]
  
  X0_train <- as.matrix(train0[, x_cols])
  X1_train <- as.matrix(train1[, x_cols])
  X_train <- as.matrix(train_data[, x_cols])
  
  y0_train <- train0$Y
  y1_train <- train1$Y
  
  X_test <- as.matrix(test_data[, x_cols])
  
  # fit response models and construct pseudo outcomes
  model_0 <- base_learner_mu$fit(X0_train, y0_train)
  model_1 <- base_learner_mu$fit(X1_train, y1_train)
  
  d0 <- base_learner_mu$predict(model_1, X0_train) - y0_train
  d1 <- y1_train - base_learner_mu$predict(model_0, X1_train)
  
  tau0_model <- base_learner_tau$fit(X0_train, d0)
  tau1_model <- base_learner_tau$fit(X1_train, d1)
  
  pi_model <- glm(T ~ ., data = train_data[, c("T", x_cols)], family = binomial())
  
  tau0_hat <- base_learner_tau$predict(tau0_model, X_test)
  tau1_hat <- base_learner_tau$predict(tau1_model, X_test)
  pi_hat <- predict(pi_model, newdata = test_data[, x_cols], type = "response")
  
  tau_hat <- pi_hat * tau0_hat + (1-pi_hat)* tau1_hat
  
  list(
    tau_hat = tau_hat,
    tau0_hat = tau0_hat,
    tau1_hat = tau1_hat
  )
}

fit_dr_learner <- function(train_data, test_data, base_learner, K=2) {
  # fit DR-learner, Kennedy (2023)
  x_cols <- get_covariates_names(train_data)
  
  X_train <- as.matrix(train_data[, x_cols])
  X_test  <- as.matrix(test_data[, x_cols])
  y_train <- train_data$Y
  t_train <- train_data$T
  
  n <- nrow(train_data)
  
  # create K folds
  fold_id <- sample(rep(1:K, length.out = n))
  
  # store nuisance predictions over iterations of the two folds here
  mu0_hat_train <- rep(NA_real_, n)
  mu1_hat_train <- rep(NA_real_, n)
  pi_hat_train  <- rep(NA_real_, n)
  
  for (k in 1:K) {
    idx_pred <- which(fold_id == k)
    idx_fit <- which(fold_id != k)
    
    fit_data <- train_data[idx_fit, ]
    pred_data <- train_data[idx_pred, ]
    
    fit0 <- fit_data[fit_data$T == 0, ]
    fit1 <- fit_data[fit_data$T == 1, ]
    
    X0_fit <- as.matrix(fit0[, x_cols])
    X1_fit <- as.matrix(fit1[, x_cols])
    X_pred  <- as.matrix(pred_data[, x_cols])
    
    y0_fit <- fit0$Y
    y1_fit <- fit1$Y
    
    # fit mu models on training fold
    model_0 <- base_learner$fit(X0_fit, y0_fit)
    model_1 <- base_learner$fit(X1_fit, y1_fit)
    
    # predict on the other fold
    mu0_hat_train[idx_pred] <- base_learner$predict(model_0, X_pred)
    mu1_hat_train[idx_pred] <- base_learner$predict(model_1, X_pred)
    
    # fit pi model on training fold
    pi_model <- glm(T ~ ., data = fit_data[, c("T", x_cols)], family = binomial())
    pi_hat_train[idx_pred] <- predict(pi_model, newdata = pred_data[, x_cols], type = "response")
  }
  
  # clip propensity scores for numerical stability
  pi_hat_train <- pmin(pmax(pi_hat_train, 0.01), 0.99)
  
  # construct DR pseudo-outcomes
  pseudo_outcome <- (mu1_hat_train - mu0_hat_train) +
    t_train * (y_train - mu1_hat_train) / pi_hat_train -
    (1 - t_train) * (y_train - mu0_hat_train) / (1 - pi_hat_train)
  
  # final regression
  tau_model <- base_learner$fit(X_train, pseudo_outcome)
  
  # predict CATE on test set
  tau_hat <- base_learner$predict(tau_model, X_test)
  
  list(
    tau_hat = tau_hat,
    pseudo_outcome = pseudo_outcome
  )
}


